processors_to_run: all
data_split: validation
workspace_dir: /workspace/nemo_capstone
final_manifest: ${workspace_dir}/manifest.json

processors:
  - _target_: sdp.processors.CreateInitialManifestFleurs
    output_manifest_file: ${workspace_dir}/${data_split}_manifest0.json
    language_id: hy_am
    data_split: ${data_split}
    raw_data_dir: ${workspace_dir}/data/fleurs_hy/${data_split} 

